export const GET_EARTHQUAKES_REQUEST = 'GET_EARTHQUAKES_REQUEST';
export const GET_EARTHQUAKES_SUCCESS = 'GET_EARTHQUAKES_SUCCESS';
export const GET_EARTHQUAKES_FAIL = 'GET_EARTHQUAKES_FAIL';
export const GET_EARTHQUAKES_RESET = 'GET_EARTHQUAKES_RESET';

export const GET_EARTHQUAKES_DIFFERENT_DATE_REQUEST =
  'GET_EARTHQUAKES_DIFFERENT_DATE_REQUEST';
export const GET_EARTHQUAKES_DIFFERENT_DATE_SUCCESS =
  'GET_EARTHQUAKES_DIFFERENT_DATE_SUCCESS';
export const GET_EARTHQUAKES_DIFFERENT_DATE_FAIL =
  'GET_EARTHQUAKES_DIFFERENT_DATE_FAIL';
